dist: trusty

language: java

jdk:
  - oraclejdk13

services:
  - postgresql
  
addons:
  postgresql: "9.5"

install: true

env:
 global:
   - CODECOV_TOKEN="6e779bc1-fde9-41a9-badd-5972e846ffaa"

before_install:
  - psql -c 'create database "buy_manager";' -U postgres

script:
  - chmod +x ./.ci/script.sh 
  - ./.ci/script.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)
