dist: trusty

language: java

jdk:
  - oraclejdk13

services:
  - postgresql
  
addons:
  sonarcloud:
    organization: "muriloalvesdev"
    token:
      secure: c98c10e52375bd7d839cc983a1169cfb1281baa1
      
addons:
  postgresql: "9.5"

install: true

before_install:
  - psql -c 'create database "buy_manager";' -U postgres

script:
  - chmod +x ./.ci/script.sh 
  - ./.ci/script.sh
